I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/gluttony.rpy", line 291, in script
    jump runintojosh
ScriptError: could not find label 'runintojosh'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/gluttony.rpy", line 291, in script
    jump runintojosh
  File "C:\Users\Kimberly\Pictures\Renpy\renpy-7.3.5-sdk\renpy\ast.py", line 1697, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\Kimberly\Pictures\Renpy\renpy-7.3.5-sdk\renpy\script.py", line 898, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'runintojosh'.

Windows-8-6.2.9200
Ren'Py 7.3.5.606
CU_HEdoubleL 1.0
Wed Apr 15 17:49:28 2020
